name: id3
description: Extract metatags from mp3 file
version: 0.0.1
author: Sanket Chaudhari<chaudharisanket2000@gmail.com>
homepage: https://github.com/sanket143/id3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter