name: id3
description: A cross platform dart package to extract meta data from mp3 files.
version: 0.1.4
homepage: https://github.com/sanket143/id3

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  test: ^1.6.5